# This is a basic workflow to help you get started with Actions

name: Hourly Update


on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1 * * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.TOKEN }}
    - name: Execute Shell Script
      run: |
        pwd
        chmod +x . ../auto.sh
        . ../auto.sh
              
              
