# This is a basic workflow to help you get started with Actions

name: Hourly Update
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1 * * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
    - name: Execute Shell Script
      run: |
        cd ..
        chmod 777 auto.sh
        . auto.sh
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
              
